/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.edu.bibliotecadesktop.view;

import br.com.edu.bibliotecadesktop.conexao.EditoraDAO;
import br.com.edu.bibliotecadesktop.dto.EditoraDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alecksandre
 */
public class friEditora extends javax.swing.JInternalFrame {

    /**
     * Creates new form friEditora
     */
    public friEditora() {
        initComponents();
        listarEditoras();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdEditora = new javax.swing.JTextField();
        txtNomeEditora = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEditora = new javax.swing.JTable();
        btnCadastrarEditora = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnEditarEditora = new javax.swing.JButton();
        btnRemoverEditora = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro da Editora");

        jLabel1.setText("Código:");

        jLabel2.setText("Nome:");

        txtIdEditora.setEnabled(false);

        tbEditora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbEditora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEditoraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbEditora);
        if (tbEditora.getColumnModel().getColumnCount() > 0) {
            tbEditora.getColumnModel().getColumn(0).setMinWidth(20);
            tbEditora.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        btnCadastrarEditora.setText("Cadastrar");
        btnCadastrarEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarEditoraActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnEditarEditora.setText("Editar");
        btnEditarEditora.setEnabled(false);
        btnEditarEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEditoraActionPerformed(evt);
            }
        });

        btnRemoverEditora.setText("Remover");
        btnRemoverEditora.setEnabled(false);
        btnRemoverEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverEditoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeEditora)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCadastrarEditora)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEditarEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnRemoverEditora)))
                                .addGap(0, 35, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarEditora)
                    .addComponent(btnLimpar)
                    .addComponent(btnEditarEditora)
                    .addComponent(btnRemoverEditora))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCadastrarEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarEditoraActionPerformed
        // TODO add your handling code here:
        Cadastrar();
        limparCampos();
        listarEditoras();
    }//GEN-LAST:event_btnCadastrarEditoraActionPerformed

    private void tbEditoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEditoraMouseClicked
        // Selectiona um dado da tabela para editá-lo
        DefaultTableModel tabela = (DefaultTableModel) tbEditora.getModel();
        //define os dados para o campo texto
        String cmpId = tabela.getValueAt(tbEditora.getSelectedRow(), 0).toString();
        String cmpNome = tabela.getValueAt(tbEditora.getSelectedRow(), 1).toString();
        //captura os campos textos.
        txtIdEditora.setText(cmpId);
        txtNomeEditora.setText(cmpNome);
        //habilita e desabilita botões.
        btnCadastrarEditora.setEnabled(false);
        btnEditarEditora.setEnabled(true);
        btnRemoverEditora.setEnabled(true);
    }//GEN-LAST:event_tbEditoraMouseClicked

    private void btnEditarEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEditoraActionPerformed
        // Atualizar dado no banco
        Editar();
        limparCampos();
        listarEditoras();
    }//GEN-LAST:event_btnEditarEditoraActionPerformed

    private void btnRemoverEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverEditoraActionPerformed
        // TODO add your handling code here:
        Object[] opt = {"Sim", "Não"};
        if (JOptionPane.showOptionDialog(null, "Deseja excluir do Banco de dados?", "Aviso", JOptionPane.DEFAULT_OPTION,
                JOptionPane.WARNING_MESSAGE, null, opt, opt[0]) == JOptionPane.YES_OPTION) {
            Deletar();
            limparCampos();
            listarEditoras();
        }
        limparCampos();
        listarEditoras();
    }//GEN-LAST:event_btnRemoverEditoraActionPerformed

    public void limparCampos() {
        //limpa os campos textfield
        txtIdEditora.setText("");
        txtNomeEditora.setText("");
        //habilita e desabilita botões.
        btnCadastrarEditora.setEnabled(true);
        btnEditarEditora.setEnabled(false);
        btnRemoverEditora.setEnabled(false);
    }

    public void Cadastrar() {
        // coleta o dado do textfield
        String nomeEditora = txtNomeEditora.getText();
        EditoraDTO editoraDto = new EditoraDTO();
        editoraDto.setNome(nomeEditora);

        EditoraDAO editoraDao = new EditoraDAO();
        editoraDao.CadastrarEditora(editoraDto);
    }

    public void Editar() {
        Long idEditora = Long.parseLong(txtIdEditora.getText());
        String nomeEditora = txtNomeEditora.getText();
        EditoraDTO editoraDto = new EditoraDTO();
        editoraDto.setId(idEditora);
        editoraDto.setNome(nomeEditora);

        EditoraDAO editoraDao = new EditoraDAO();
        editoraDao.AtualizarEditora(editoraDto);
    }

    public void Deletar() {
        Long idEditora = Long.parseLong(txtIdEditora.getText());
        EditoraDTO editoraDto = new EditoraDTO();
        editoraDto.setId(idEditora);

        EditoraDAO editoraDao = new EditoraDAO();
        editoraDao.DeletarEditora(editoraDto);
    }

    public void listarEditoras() {
        //consulta todos os dados da tabela editora 
        try {
            EditoraDAO editoraDao = new EditoraDAO();
            DefaultTableModel tabela = (DefaultTableModel) tbEditora.getModel();
            tabela.setNumRows(0);
            ArrayList<EditoraDTO> lista = editoraDao.PesquisarEditora();
            for (int i = 0; i < lista.size(); i++) {
                tabela.addRow(new Object[]{
                    lista.get(i).getId(),
                    lista.get(i).getNome()
                });
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Consultar dados da tabela Editora:" + erro);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarEditora;
    private javax.swing.JButton btnEditarEditora;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnRemoverEditora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbEditora;
    private javax.swing.JTextField txtIdEditora;
    private javax.swing.JTextField txtNomeEditora;
    // End of variables declaration//GEN-END:variables
}
